// Mocks generated by Mockito 5.4.6 from annotations
// in maikago/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:maikago/models/list.dart' as _i4;
import 'package:maikago/models/shop.dart' as _i5;
import 'package:maikago/services/data_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [DataService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDataService extends _i1.Mock implements _i2.DataService {
  MockDataService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> saveItem(
    _i4.ListItem? item, {
    bool? isAnonymous = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveItem,
          [item],
          {#isAnonymous: isAnonymous},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateItem(
    _i4.ListItem? item, {
    bool? isAnonymous = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateItem,
          [item],
          {#isAnonymous: isAnonymous},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteItem(
    String? itemId, {
    bool? isAnonymous = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteItem,
          [itemId],
          {#isAnonymous: isAnonymous},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Stream<List<_i4.ListItem>> getItems({bool? isAnonymous = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getItems,
          [],
          {#isAnonymous: isAnonymous},
        ),
        returnValue: _i3.Stream<List<_i4.ListItem>>.empty(),
      ) as _i3.Stream<List<_i4.ListItem>>);

  @override
  _i3.Future<List<_i4.ListItem>> getItemsOnce({bool? isAnonymous = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getItemsOnce,
          [],
          {#isAnonymous: isAnonymous},
        ),
        returnValue: _i3.Future<List<_i4.ListItem>>.value(<_i4.ListItem>[]),
      ) as _i3.Future<List<_i4.ListItem>>);

  @override
  _i3.Future<void> saveShop(
    _i5.Shop? shop, {
    bool? isAnonymous = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveShop,
          [shop],
          {#isAnonymous: isAnonymous},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateShop(
    _i5.Shop? shop, {
    bool? isAnonymous = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShop,
          [shop],
          {#isAnonymous: isAnonymous},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteShop(
    String? shopId, {
    bool? isAnonymous = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteShop,
          [shopId],
          {#isAnonymous: isAnonymous},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Stream<List<_i5.Shop>> getShops({bool? isAnonymous = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getShops,
          [],
          {#isAnonymous: isAnonymous},
        ),
        returnValue: _i3.Stream<List<_i5.Shop>>.empty(),
      ) as _i3.Stream<List<_i5.Shop>>);

  @override
  _i3.Future<List<_i5.Shop>> getShopsOnce({bool? isAnonymous = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getShopsOnce,
          [],
          {#isAnonymous: isAnonymous},
        ),
        returnValue: _i3.Future<List<_i5.Shop>>.value(<_i5.Shop>[]),
      ) as _i3.Future<List<_i5.Shop>>);

  @override
  _i3.Future<void> saveUserProfile(Map<String, dynamic>? profile) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveUserProfile,
          [profile],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<Map<String, dynamic>?> getUserProfile() => (super.noSuchMethod(
        Invocation.method(
          #getUserProfile,
          [],
        ),
        returnValue: _i3.Future<Map<String, dynamic>?>.value(),
      ) as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<bool> isDataSynced() => (super.noSuchMethod(
        Invocation.method(
          #isDataSynced,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> clearAnonymousSession() => (super.noSuchMethod(
        Invocation.method(
          #clearAnonymousSession,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
