-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgeZdSeI6WJph9Dn8O
qYwjCQSda9M7J9PijFtSmx4MarOgCgYIKoZIzj0DAQehRANCAATAy+48jjiK50gG
+6yzKB8rgjvUy8GTCp0WDD0cV0eAglHCsIRCnB+xKYzLUmg+b8bdB5EdgjnZtEKh
5WZHvOTk
-----END PRIVATE KEY-----