workflows:
  ios-simulator-test:
    name: iOS Simulator Test
    environment:
      flutter: stable
      xcode: 16.4
      cocoapods: 1.16.2
      vars:
        DEV_EMAIL: "kensaku.ikeda04@gmail.com"  # 実際のメールアドレスに変更してください
        GOOGLE_SERVICE_INFO_PLIST: $GOOGLE_SERVICE_INFO_PLIST
    scripts:
      - name: Flutter setup
        script: |
          flutter --version
          flutter clean
          flutter packages pub get
          flutter doctor -v
      
      - name: Code analysis
        script: |
          flutter analyze --no-fatal-infos || true
          flutter test || echo "Tests failed but continuing with build"
      
      - name: Create GoogleService-Info.plist
        script: |
          echo "$GOOGLE_SERVICE_INFO_PLIST" > ios/Runner/GoogleService-Info.plist
      
      - name: iOS build
        script: |
          cd ios
          pod deintegrate
          pod cache clean --all
          pod repo update
          pod install --repo-update --verbose
          cd ..
          # Validate all plist files before building
          find ios -name "*.plist" -exec plutil -lint {} \;
          flutter build ios --simulator --debug --no-codesign --verbose
      
      - name: Build verification
        script: |
          echo "iOS build completed successfully"
          ls -la build/ios/iphonesimulator/
    
    artifacts:
      - build/ios/iphonesimulator/*.app
      - build/ios/iphonesimulator/*.dSYM.zip
      - flutter_drive.log
    
    publishing:
      email:
        recipients:
          - $DEV_EMAIL
        notify:
          success: true
          failure: true
      
  android-build:
    name: Android Build
    environment:
      flutter: stable
      android_signing:
        - keystore_reference
      vars:
        DEV_EMAIL: "kensaku.ikeda04@gmail.com"  # 実際のメールアドレスに変更してください
    scripts:
      - name: Flutter setup
        script: |
          flutter --version
          flutter packages pub get
          flutter doctor -v
      
      - name: Code analysis
        script: |
          flutter analyze --no-fatal-infos || true
          flutter test || echo "Tests failed but continuing with build"
      
      - name: Android build
        script: |
          flutter build apk --debug
          flutter build appbundle --debug
    
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    
    publishing:
      email:
        recipients:
          - $DEV_EMAIL
        notify:
          success: true
          failure: true
