workflows:
  ios-release:
    name: iOS Release
    environment:
      flutter: stable
      xcode: 16.4
      cocoapods: 1.16.2
      groups:
        - ios_signing
      vars:
        DEV_EMAIL: "kensaku.ikeda04@gmail.com"
        GOOGLE_SERVICE_INFO_PLIST: $GOOGLE_SERVICE_INFO_PLIST
        BUNDLE_ID: "com.ikcoding.maikago"
    integrations:
      app_store_connect: "Codemagic Connect Key"
    instance_type: mac_mini_m1
    scripts:
      - name: Set up keychain to be used for codesigning
        script: |
          keychain initialize

      - name: Set up signing certificate and provisioning profile
        script: |
          app-store-connect fetch-signing-files $BUNDLE_ID \
            --type IOS_APP_STORE \
            --create \
            --certificate-key @env:CERTIFICATE_PRIVATE_KEY
          keychain add-certificates

      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles

      - name: Get Flutter packages
        script: |
          flutter packages pub get

      - name: Create GoogleService-Info.plist
        script: |
          echo "$GOOGLE_SERVICE_INFO_PLIST" > ios/Runner/GoogleService-Info.plist

      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;

      - name: Flutter analyze
        script: |
          flutter analyze

      - name: Flutter unit tests
        script: |
          flutter test

      - name: Build ipa for distribution
        script: |
          flutter build ipa --release \
            --build-name=1.4.1 \
            --build-number=57

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
        beta_groups:
          - "Internal Testing"
      email:
        recipients:
          - $DEV_EMAIL
        notify:
          success: true
          failure: true
