// Mocks generated by Mockito 5.4.6 from annotations
// in maikago/test/widgets/migration_status_widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:ui' as _i2;

import 'package:flutter/material.dart' as _i3;
import 'package:maikago/services/subscription_integration_service.dart' as _i4;
import 'package:maikago/services/subscription_manager.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeColor_0 extends _i1.SmartFake implements _i2.Color {
  _FakeColor_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIconData_1 extends _i1.SmartFake implements _i3.IconData {
  _FakeIconData_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SubscriptionIntegrationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSubscriptionIntegrationService extends _i1.Mock
    implements _i4.SubscriptionIntegrationService {
  MockSubscriptionIntegrationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  bool get hasBenefits =>
      (super.noSuchMethod(Invocation.getter(#hasBenefits), returnValue: false)
          as bool);

  @override
  bool get shouldHideAds =>
      (super.noSuchMethod(Invocation.getter(#shouldHideAds), returnValue: false)
          as bool);

  @override
  bool get shouldShowAds =>
      (super.noSuchMethod(Invocation.getter(#shouldShowAds), returnValue: false)
          as bool);

  @override
  bool get canChangeTheme =>
      (super.noSuchMethod(
            Invocation.getter(#canChangeTheme),
            returnValue: false,
          )
          as bool);

  @override
  bool get canChangeFont =>
      (super.noSuchMethod(Invocation.getter(#canChangeFont), returnValue: false)
          as bool);

  @override
  bool get isDonated =>
      (super.noSuchMethod(Invocation.getter(#isDonated), returnValue: false)
          as bool);

  @override
  int get totalDonationAmount =>
      (super.noSuchMethod(
            Invocation.getter(#totalDonationAmount),
            returnValue: 0,
          )
          as int);

  @override
  String get donorTitle =>
      (super.noSuchMethod(
            Invocation.getter(#donorTitle),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#donorTitle),
            ),
          )
          as String);

  @override
  _i2.Color get donorTitleColor =>
      (super.noSuchMethod(
            Invocation.getter(#donorTitleColor),
            returnValue: _FakeColor_0(
              this,
              Invocation.getter(#donorTitleColor),
            ),
          )
          as _i2.Color);

  @override
  _i3.IconData get donorTitleIcon =>
      (super.noSuchMethod(
            Invocation.getter(#donorTitleIcon),
            returnValue: _FakeIconData_1(
              this,
              Invocation.getter(#donorTitleIcon),
            ),
          )
          as _i3.IconData);

  @override
  _i6.SubscriptionPlan get currentPlan =>
      (super.noSuchMethod(
            Invocation.getter(#currentPlan),
            returnValue: _i6.SubscriptionPlan.free,
          )
          as _i6.SubscriptionPlan);

  @override
  String get currentPlanName =>
      (super.noSuchMethod(
            Invocation.getter(#currentPlanName),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#currentPlanName),
            ),
          )
          as String);

  @override
  int get currentPlanPrice =>
      (super.noSuchMethod(Invocation.getter(#currentPlanPrice), returnValue: 0)
          as int);

  @override
  bool get isSubscriptionActive =>
      (super.noSuchMethod(
            Invocation.getter(#isSubscriptionActive),
            returnValue: false,
          )
          as bool);

  @override
  bool get isSubscriptionExpired =>
      (super.noSuchMethod(
            Invocation.getter(#isSubscriptionExpired),
            returnValue: false,
          )
          as bool);

  @override
  int get maxLists =>
      (super.noSuchMethod(Invocation.getter(#maxLists), returnValue: 0) as int);

  @override
  List<String> get familyMembers =>
      (super.noSuchMethod(
            Invocation.getter(#familyMembers),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  bool get hasFamilySharing =>
      (super.noSuchMethod(
            Invocation.getter(#hasFamilySharing),
            returnValue: false,
          )
          as bool);

  @override
  int get maxFamilyMembers =>
      (super.noSuchMethod(Invocation.getter(#maxFamilyMembers), returnValue: 0)
          as int);

  @override
  int get availableThemes =>
      (super.noSuchMethod(Invocation.getter(#availableThemes), returnValue: 0)
          as int);

  @override
  int get availableFonts =>
      (super.noSuchMethod(Invocation.getter(#availableFonts), returnValue: 0)
          as int);

  @override
  bool get isRestoring =>
      (super.noSuchMethod(Invocation.getter(#isRestoring), returnValue: false)
          as bool);

  @override
  bool get isLegacyDonor =>
      (super.noSuchMethod(Invocation.getter(#isLegacyDonor), returnValue: false)
          as bool);

  @override
  bool get migrationCompleted =>
      (super.noSuchMethod(
            Invocation.getter(#migrationCompleted),
            returnValue: false,
          )
          as bool);

  @override
  bool get isNewUser =>
      (super.noSuchMethod(Invocation.getter(#isNewUser), returnValue: false)
          as bool);

  @override
  bool get shouldRecommendSubscription =>
      (super.noSuchMethod(
            Invocation.getter(#shouldRecommendSubscription),
            returnValue: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void setCurrentUserId(String? userId) => super.noSuchMethod(
    Invocation.method(#setCurrentUserId, [userId]),
    returnValueForMissingStub: null,
  );

  @override
  bool canCreateList(int? currentListCount) =>
      (super.noSuchMethod(
            Invocation.method(#canCreateList, [currentListCount]),
            returnValue: false,
          )
          as bool);

  @override
  bool isThemeAvailable(int? themeIndex) =>
      (super.noSuchMethod(
            Invocation.method(#isThemeAvailable, [themeIndex]),
            returnValue: false,
          )
          as bool);

  @override
  bool isFontAvailable(int? fontIndex) =>
      (super.noSuchMethod(
            Invocation.method(#isFontAvailable, [fontIndex]),
            returnValue: false,
          )
          as bool);

  @override
  bool canAddFamilyMember() =>
      (super.noSuchMethod(
            Invocation.method(#canAddFamilyMember, []),
            returnValue: false,
          )
          as bool);

  @override
  _i7.Future<void> processDonation(int? amount) =>
      (super.noSuchMethod(
            Invocation.method(#processDonation, [amount]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> restoreDonationStatus() =>
      (super.noSuchMethod(
            Invocation.method(#restoreDonationStatus, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> resetDonationStatus() =>
      (super.noSuchMethod(
            Invocation.method(#resetDonationStatus, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> processSubscription(
    _i6.SubscriptionPlan? plan, {
    DateTime? expiry,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#processSubscription, [plan], {#expiry: expiry}),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> restoreSubscriptionStatus() =>
      (super.noSuchMethod(
            Invocation.method(#restoreSubscriptionStatus, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> resetSubscriptionStatus() =>
      (super.noSuchMethod(
            Invocation.method(#resetSubscriptionStatus, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> addFamilyMember(String? memberEmail) =>
      (super.noSuchMethod(
            Invocation.method(#addFamilyMember, [memberEmail]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> removeFamilyMember(String? memberEmail) =>
      (super.noSuchMethod(
            Invocation.method(#removeFamilyMember, [memberEmail]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  Map<String, dynamic> getPlanInfo(_i6.SubscriptionPlan? plan) =>
      (super.noSuchMethod(
            Invocation.method(#getPlanInfo, [plan]),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  Map<_i6.SubscriptionPlan, Map<String, dynamic>> getAllPlans() =>
      (super.noSuchMethod(
            Invocation.method(#getAllPlans, []),
            returnValue: <_i6.SubscriptionPlan, Map<String, dynamic>>{},
          )
          as Map<_i6.SubscriptionPlan, Map<String, dynamic>>);

  @override
  Map<String, dynamic> getMigrationStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getMigrationStatus, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  String getMigrationRecommendationMessage() =>
      (super.noSuchMethod(
            Invocation.method(#getMigrationRecommendationMessage, []),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.method(#getMigrationRecommendationMessage, []),
            ),
          )
          as String);

  @override
  _i6.SubscriptionPlan getRecommendedPlan() =>
      (super.noSuchMethod(
            Invocation.method(#getRecommendedPlan, []),
            returnValue: _i6.SubscriptionPlan.free,
          )
          as _i6.SubscriptionPlan);

  @override
  _i7.Future<void> completeMigration() =>
      (super.noSuchMethod(
            Invocation.method(#completeMigration, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> setAsNewUser() =>
      (super.noSuchMethod(
            Invocation.method(#setAsNewUser, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> setAsLegacyDonor() =>
      (super.noSuchMethod(
            Invocation.method(#setAsLegacyDonor, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void debugPrintStatus() => super.noSuchMethod(
    Invocation.method(#debugPrintStatus, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i2.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i2.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
